export const NAV_CLICK_HANDLER = "NAV_CLICK_HANDLER";
export const NAV_MOUSEOVER_HANDLER = "NAV_MOUSEOVER_HANDLER";
export const NAV_MOUSEOUT_HANDLER = "NAV_MOUSEOUT_HANDLER";
export const MOUSE_MOVE = "MOUSE_MOVE";
export const BUTTON_CLICK_HANDLER = "BUTTON_CLICK_HANDLER";
export const PAGE_EXIT_HANDLER = "PAGE_EXIT_HANDLER";
export const STACK_CLICK_HANDLER = "STACK_CLICK_HANDLER";
export const ON_SCROLL_HANDLER = "ON_SCROLL_HANDLER";
export const SET_STATE = 'SET_STATE';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const SET_HOVER = 'SET_HOVER';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';