export const NAV_CLICK_HANDLER = "NAV_CLICK_HANDLER";
export const NAV_MOUSEOVER_HANDLER = "NAV_MOUSEOVER_HANDLER";
export const NAV_MOUSEOUT_HANDLER = "NAV_MOUSEOUT_HANDLER";
export const MOUSE_MOVE = "MOUSE_MOVE";
export const BUTTON_CLICK_HANDLER = "BUTTON_CLICK_HANDLER";
export const PAGE_EXIT_HANDLER = "PAGE_EXIT_HANDLER";
export const STACK_CLICK_HANDLER = "STACK_CLICK_HANDLER";
export const ON_SCROLL_HANDLER = "ON_SCROLL_HANDLER";
export const SET_STATE = 'SET_STATE';

